### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-2-legacy#16]
Probably include snippets from the "Road to 3.0" blog post, and a cross link.

Maybe more?

**Comment by thoov** [comment]
Ya for me I would want to see sections for the following: 

- What this addon is trying to do and when should it or should not be used
- What APIs / deprecations are covered in this addon
- How to turn them on / off (via config)
- Links to the [deprecations site](https://www.emberjs.com/deprecations/v2.x/) for more info and migration paths
