### ISSUE TITLE
Update deprecations page with links to this repo

### ISSUE THREAD

**Issue by thoov** [emberjs/ember-2-legacy#38]
Like done here: https://www.emberjs.com/deprecations/v2.x/#toc_legacy-support-addons

**Comment by locks** [comment]
Can you open an issue on the website repo with the itemised list?

**Comment by thoov** [comment]
This is the tracking issue now: https://github.com/emberjs/website/issues/3121

**Comment by jenweber** [comment]
resolved, issue can be closed
