### ISSUE TITLE
Provide addon's own public build time API for enabling/disabling deprecations

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-2-legacy#60]
The internal usage of underscored `EmberENV` properties for toggling deprecated features should not be made to seem as public API (we currently mention in our README).

Instead, we should provide our own build time API to allow toggling. Something like:

```js
new EmberApp(defaults, {
  'ember-2-legacy': {
    'underscore-actions-support': false
  }
})
```

The default for each item would be `true`, and you'd override with `false` to disable a given legacy feature.

**Comment by thoov** [comment]
Working on this now
